### ISSUE TITLE
Compile OL2Utils to Windows (7)

### ISSUE THREAD

**Issue by TrikzMe** [nnvt/OL2Utils#1]
Hi nnvt!

Can you please say me how to compile your projects to windows?
I don't know how to do it.
I have installed Visual Studio 2017 + CMake.
I did few researchs to compile your project, I even tried with AppVeyor but I still can't compile it...

Thank you for your work and answer :)

**Comment by CppBunny** [comment]
I'm not sure how to do it with visual studio as I usually use either a machine running linux or the built in linux vm on windows 10. I'll do some research on how to do it with vs though.

Also what is it exactly that you are trying to do? This is currently not yet operational and it seems like getting UPKUtils to work with Outlast 2 it is a little above my skill level, maybe you could help me?

**Comment by TrikzMe** [comment]
To be honnest I'm interesting in extracting models/textures and maybe animations.
I saw someone on deviantart extracted models with oribinal bones.
I made some researchs to see who could create a tool for Outlast II then I saw your page.
I am not a developper sadly so I don't think I'm able to help... Sorry.

**Comment by TrikzMe** [comment]
Well, I found a way to get what I want (not an extract tool).
Fell free to remove this report^^
Thank you for your time :)
